services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scentricity_backend:/backend
    environment:
      DB_HOST: database
      DB_NAME: scents
      DB_USER: scent_user
      DB_PASS: password
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: "scents"
      POSTGRES_USER: "scent_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "9999:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data


  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./scentricity_frontend:/frontend
    command: >
      sh -c "npm run serve"
    depends_on:
      - backend

  stripe:
    image: stripe/stripe-cli:latest
    entrypoint: /bin/sh
    tty: true
    stdin_open: true
    volumes:
      - ~/.config/stripe:/root/.config/stripe
    depends_on:
      - backend

volumes:
  pg_data: