# Generated by Django 4.2.7 on 2024-04-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_product_productproperty_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='choice_value',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float')], default='string', max_length=20),
        ),
    ]
