# Generated by Django 4.2.7 on 2024-04-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_productproperty_choice_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='float_value',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='bool_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('bool', 'Boolean')], default='string', max_length=20),
        ),
    ]
