# Generated by Django 4.2.7 on 2024-04-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_productproperty_bool_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='value',
            field=models.CharField(blank=True, null=True),
        ),
    ]
