# Generated by Django 4.2.7 on 2024-04-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='properties',
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='store.product'),
        ),
    ]
