# Generated by Django 4.2.7 on 2024-04-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_product_property_productproperty_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='None', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.category'),
        ),
    ]
