# Generated by Django 4.2.7 on 2024-04-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='NONAME', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.brand'),
        ),
    ]
