# Generated by Django 4.2.7 on 2024-04-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
